spring:
    datasource:
        url: jdbc:postgresql://localhost:5434/user-app-db
        username: alex
        password: alex
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
